### ISSUE TITLE
Mannschaftswertung

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#574]
Es soll eine Mannschaftswertung unterstützt werden.

**Comment by mstenz** [comment]
Benötigte Funktionen für Mannschaftswertung:

- Erlaube die Auswahl, welche Teilnehmer der Mannschaft am Ende in der Wertung erscheinen, nicht gewertete Teilnehmer können entweder angezeigt oder ausgeblendet werden
- Team kann nicht gewertet werden wenn nicht mindestens X Läufer im Ziel sind
- Zeitaufschlag auf das Team von X Sekunden (nicht einen Läufer) wenn nur 1 Geschlecht im Ziel ist (also nur Frauen oder nur Herren)
- Bei Teamlaufzeitgleichheit wird das Team mit der besseren Laufzeit der ersten Frau nach oben gesetzt, wenn alle Teams mit Punktegleichheit keine Frau haben dann zählt die Laufzeit des besten Herren.
- Gewerter werden beste Frau + Bester Mann

**Comment by svenflossmann** [comment]
**ToDo**

- [ ] Gruppierungauswahl berücksichtigen
- [ ] Team kann nicht gewertet werden wenn nicht mindestens X Läufer im Ziel sind
- [ ] Konfiguration von Anzahl der Teammitglieder (Mindestanzahl, Maximalanzahl)
- [ ] Zeitaufschlag auf das Team von X Sekunden (nicht einen Läufer) wenn nur 1 Geschlecht im Ziel ist (also nur Frauen oder nur Herren)
- [ ] Bei Teamlaufzeitgleichheit wird das Team mit der besseren Laufzeit der ersten Frau nach oben gesetzt, wenn alle Teams mit Punktegleichheit keine Frau haben dann zählt die Laufzeit des besten Herren.
    Definition, welche Plätze mit welchem Geschlecht (oder gemischt) bestützt werden müssen. Damit z.b. bei Platz 1 und Platz 2 im Team mit Frauen der Herr erst auf Platz 3 startet wenn keine Frau im Team ist.
    Anzahl der Teammitglieder (Mindestanzahl, Maximalanzahl)
